import { cn } from '@/utils/cn'
import { Open_Sans } from 'next/font/google'

import './globals.css'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'HeadlessAuth.js - Authentification without the headache',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          openSans.className,
          'selection:bg-indigo-600/40 selection:text-white'
        )}
      >
        {children}
      </body>
    </html>
  )
}
